// session
export const RECEIVE_USER = 'RECEIVE_USER';
export const RECEIVE_INITIALIZING = 'RECEIVE_INITIALIZING';
export const RECEIVE_SESSION_ERROR = 'RECEIVE_SESSION_ERROR';
export const RECEIVE_STATE = 'RECEIVE_STATE';
export const SIGN_UP = 'SIGN_UP';
export const AUTH_CHANGED = 'AUTH_CHANGED';
export const GET_STATE = 'GET_STATE';

// data
export const RECEIVE_COVID_DATA = 'RECEIVE_COVID_DATA';
export const RECEIVE_DATA_LOADING = 'RECEIVE_DATA_LOADING';
